LIBNAME=baselib.a
INCLUDES=-I$(SRCDIR)/cmn/mathlib -I$(SRCDIR)/ccd/cfg \
			-I$(SRCDIR)/cmn/datan -I. -D_NO_CURL_
include baselib.mak

include lib.mak

#$(CMNCFG) : cmn.cfg
#	@echo Copying cmn.cfg
#	cp cmn.cfg $(CMNCFG)
